on: push

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: Molecule test
        uses: robertdebock/molecule-action@1.2.4

      - name: Upload to galaxy
        uses: robertdebock/galaxy-action@1.0.3
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
